import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './globals.css';
import { config } from "../../config";
import { headers } from 'next/headers';
import { cookieToInitialState } from "wagmi";
import Web3ModalProvider from "../../context";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { ModeToggle } from "@/components/ui/darkmode";
import { motion } from "framer-motion";

// Import or define DiamondIcon here
// Adjust the path as necessary

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'));

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div style={{ position: 'relative', display: 'flex', justifyContent: 'flex-end', padding: '10px' }}>
  <ModeToggle />
</div>

          <Web3ModalProvider initialState={initialState}>
            {children}
          </Web3ModalProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
